export interface BusinessTypeConfig {
  label: string;
  icon: string;
  categories: Array<{ name: string; description: string; productCount: number }>;
  defaultProducts: Array<{
    name: string;
    price: number;
    originalPrice?: number;
    description: string;
    category: string;
    rating: number;
    reviewCount: number;
    badge?: string;
  }>;
  colorSchemes: Array<{ primary: string; secondary: string; label: string }>;
  designStyle: {
    themeStyle: string;
    fontStyle: string;
    buttonStyle: string;
    borderRadius: string;
  };
}

export const BUSINESS_TYPES: Record<string, BusinessTypeConfig> = {
  Fashion: {
    label: 'Fashion & Apparel',
    icon: '👗',
    categories: [
      { name: "Men's Wear", description: 'Shirts, trousers, jackets, and formal wear', productCount: 45 },
      { name: "Women's Wear", description: 'Dresses, tops, skirts, and ethnic wear', productCount: 62 },
      { name: 'Kids', description: 'Clothing and accessories for children', productCount: 30 },
      { name: 'Accessories', description: 'Bags, belts, scarves, and jewelry', productCount: 28 },
      { name: 'Footwear', description: 'Shoes, sandals, boots, and sneakers', productCount: 35 },
      { name: 'Seasonal Collection', description: 'Summer, winter, and festive collections', productCount: 20 },
    ],
    defaultProducts: [
      { name: 'Classic Oxford Shirt', price: 49.99, originalPrice: 69.99, description: 'Premium cotton oxford shirt with a modern fit', category: "Men's Wear", rating: 4.5, reviewCount: 234, badge: 'Best Seller' },
      { name: 'Floral Summer Dress', price: 79.99, description: 'Lightweight floral print dress perfect for summer', category: "Women's Wear", rating: 4.7, reviewCount: 189, badge: 'New' },
      { name: 'Leather Crossbody Bag', price: 89.99, originalPrice: 120.00, description: 'Genuine leather crossbody with adjustable strap', category: 'Accessories', rating: 4.3, reviewCount: 156 },
      { name: 'Running Sneakers Pro', price: 129.99, description: 'Lightweight performance sneakers with cushion support', category: 'Footwear', rating: 4.6, reviewCount: 312, badge: 'Trending' },
      { name: 'Denim Jacket Classic', price: 99.99, originalPrice: 139.99, description: 'Timeless denim jacket with vintage wash', category: "Men's Wear", rating: 4.4, reviewCount: 198 },
      { name: 'Kids Rainbow T-Shirt', price: 24.99, description: 'Soft cotton t-shirt with fun rainbow print', category: 'Kids', rating: 4.8, reviewCount: 87 },
      { name: 'Silk Scarf Luxury', price: 59.99, description: 'Hand-printed pure silk scarf', category: 'Accessories', rating: 4.2, reviewCount: 65 },
      { name: 'Ankle Boots Suede', price: 149.99, originalPrice: 189.99, description: 'Premium suede ankle boots with side zip', category: 'Footwear', rating: 4.5, reviewCount: 143, badge: 'Limited' },
      { name: 'Ethnic Kurta Set', price: 69.99, description: 'Elegant embroidered kurta with palazzo pants', category: "Women's Wear", rating: 4.6, reviewCount: 201 },
      { name: 'Wool Blend Overcoat', price: 199.99, originalPrice: 279.99, description: 'Warm wool blend overcoat for winter', category: "Men's Wear", rating: 4.4, reviewCount: 89 },
    ],
    colorSchemes: [
      { primary: '#C2185B', secondary: '#F8BBD0', label: 'Rose Elegance' },
      { primary: '#212121', secondary: '#F5F5F5', label: 'Monochrome Chic' },
      { primary: '#5D4037', secondary: '#D7CCC8', label: 'Earthy Warmth' },
      { primary: '#1A237E', secondary: '#C5CAE9', label: 'Royal Indigo' },
    ],
    designStyle: {
      themeStyle: 'Elegant',
      fontStyle: 'Playfair Display',
      buttonStyle: 'Rounded',
      borderRadius: '12px',
    },
  },

  Electronics: {
    label: 'Electronics & Tech',
    icon: '📱',
    categories: [
      { name: 'Smartphones', description: 'Latest smartphones and accessories', productCount: 35 },
      { name: 'Laptops', description: 'Laptops, notebooks, and ultrabooks', productCount: 28 },
      { name: 'Audio', description: 'Headphones, speakers, and sound systems', productCount: 42 },
      { name: 'Gaming', description: 'Consoles, gaming PCs, and accessories', productCount: 38 },
      { name: 'Cameras', description: 'DSLR, mirrorless, and action cameras', productCount: 22 },
      { name: 'Wearables', description: 'Smartwatches, fitness trackers, and VR', productCount: 25 },
    ],
    defaultProducts: [
      { name: 'ProMax Smartphone 15', price: 999.99, originalPrice: 1099.99, description: '6.7" OLED, A17 chip, 48MP camera system', category: 'Smartphones', rating: 4.7, reviewCount: 1243, badge: 'Best Seller' },
      { name: 'UltraSlim Laptop 14"', price: 1299.99, description: 'Intel i7, 16GB RAM, 512GB SSD, Thunderbolt 4', category: 'Laptops', rating: 4.6, reviewCount: 567, badge: 'Editor\'s Choice' },
      { name: 'Wireless Noise-Canceling Headphones', price: 349.99, originalPrice: 399.99, description: '30hr battery, adaptive ANC, hi-res audio', category: 'Audio', rating: 4.8, reviewCount: 892, badge: 'Top Rated' },
      { name: 'Gaming Console Pro', price: 499.99, description: '4K gaming, 1TB SSD, ray tracing support', category: 'Gaming', rating: 4.5, reviewCount: 2341, badge: 'Hot Deal' },
      { name: 'Mirrorless Camera Kit', price: 1499.99, originalPrice: 1799.99, description: '26MP sensor, 4K video, 24-70mm lens included', category: 'Cameras', rating: 4.7, reviewCount: 345 },
      { name: 'Smartwatch Series 8', price: 399.99, description: 'Health monitoring, GPS, always-on display', category: 'Wearables', rating: 4.4, reviewCount: 678 },
      { name: 'Portable Bluetooth Speaker', price: 129.99, originalPrice: 159.99, description: '20hr playtime, waterproof IP67, 360° sound', category: 'Audio', rating: 4.3, reviewCount: 456 },
      { name: 'Gaming Mouse RGB', price: 79.99, description: '25K DPI sensor, 8 programmable buttons', category: 'Gaming', rating: 4.6, reviewCount: 789, badge: 'Popular' },
      { name: 'True Wireless Earbuds', price: 179.99, originalPrice: 229.99, description: 'ANC, spatial audio, 24hr total battery', category: 'Audio', rating: 4.5, reviewCount: 1567 },
      { name: '4K Ultra HD Monitor 27"', price: 599.99, description: 'HDR10, USB-C, 144Hz, factory calibrated', category: 'Laptops', rating: 4.4, reviewCount: 234 },
    ],
    colorSchemes: [
      { primary: '#1565C0', secondary: '#BBDEFB', label: 'Tech Blue' },
      { primary: '#212121', secondary: '#E0E0E0', label: 'Sleek Dark' },
      { primary: '#00897B', secondary: '#B2DFDB', label: 'Modern Teal' },
      { primary: '#37474F', secondary: '#CFD8DC', label: 'Steel Grey' },
    ],
    designStyle: {
      themeStyle: 'Modern',
      fontStyle: 'Inter',
      buttonStyle: 'Sharp',
      borderRadius: '8px',
    },
  },

  Grocery: {
    label: 'Grocery & Supermarket',
    icon: '🛒',
    categories: [
      { name: 'Fresh Produce', description: 'Fruits, vegetables, and herbs', productCount: 85 },
      { name: 'Dairy & Eggs', description: 'Milk, cheese, yogurt, and eggs', productCount: 42 },
      { name: 'Beverages', description: 'Juices, water, soft drinks, and tea', productCount: 55 },
      { name: 'Snacks', description: 'Chips, cookies, nuts, and packaged snacks', productCount: 68 },
      { name: 'Organic & Health', description: 'Organic, gluten-free, and health foods', productCount: 35 },
      { name: 'Frozen Foods', description: 'Frozen vegetables, meals, and desserts', productCount: 40 },
    ],
    defaultProducts: [
      { name: 'Organic Bananas (1 bunch)', price: 2.99, description: 'Fresh organic bananas, sourced from local farms', category: 'Fresh Produce', rating: 4.5, reviewCount: 456 },
      { name: 'Whole Milk (1 gallon)', price: 4.49, description: 'Farm-fresh whole milk, pasteurized', category: 'Dairy & Eggs', rating: 4.6, reviewCount: 789, badge: 'Fresh Daily' },
      { name: 'Sourdough Bread', price: 5.99, originalPrice: 7.49, description: 'Artisan sourdough, freshly baked', category: 'Fresh Produce', rating: 4.7, reviewCount: 234, badge: 'Best Seller' },
      { name: 'Greek Yogurt Variety Pack', price: 8.99, description: '6-pack mixed flavors, high protein', category: 'Dairy & Eggs', rating: 4.4, reviewCount: 567 },
      { name: 'Cold Pressed Orange Juice', price: 6.99, description: '100% pure squeezed, no added sugar', category: 'Beverages', rating: 4.5, reviewCount: 345 },
      { name: 'Mixed Berry Smoothie Pack', price: 9.99, originalPrice: 12.99, description: 'Frozen berries for smoothies, 2lb bag', category: 'Frozen Foods', rating: 4.3, reviewCount: 198 },
      { name: 'Trail Mix Premium', price: 7.49, description: 'Nuts, seeds, and dried fruits blend', category: 'Snacks', rating: 4.6, reviewCount: 423, badge: 'Popular' },
      { name: 'Organic Quinoa (2lb)', price: 11.99, description: 'Pre-washed organic white quinoa', category: 'Organic & Health', rating: 4.4, reviewCount: 167 },
      { name: 'Free Range Eggs (12pk)', price: 5.99, description: 'Farm fresh free range eggs', category: 'Dairy & Eggs', rating: 4.7, reviewCount: 891, badge: 'Top Rated' },
      { name: 'Sparkling Water Variety', price: 8.49, description: '12-pack assorted flavors, zero calories', category: 'Beverages', rating: 4.2, reviewCount: 312 },
    ],
    colorSchemes: [
      { primary: '#2E7D32', secondary: '#C8E6C9', label: 'Fresh Green' },
      { primary: '#F57F17', secondary: '#FFF9C4', label: 'Sunny Harvest' },
      { primary: '#4E342E', secondary: '#D7CCC8', label: 'Natural Earth' },
      { primary: '#0277BD', secondary: '#B3E5FC', label: 'Clean Blue' },
    ],
    designStyle: {
      themeStyle: 'Friendly',
      fontStyle: 'Nunito',
      buttonStyle: 'Pill',
      borderRadius: '20px',
    },
  },

  Furniture: {
    label: 'Furniture & Home',
    icon: '🛋️',
    categories: [
      { name: 'Living Room', description: 'Sofas, coffee tables, TV units, and shelving', productCount: 45 },
      { name: 'Bedroom', description: 'Beds, mattresses, wardrobes, and nightstands', productCount: 38 },
      { name: 'Office', description: 'Desks, office chairs, and storage', productCount: 32 },
      { name: 'Outdoor', description: 'Patio furniture, garden sets, and loungers', productCount: 28 },
      { name: 'Lighting', description: 'Chandeliers, lamps, pendant lights, and fixtures', productCount: 42 },
      { name: 'Decor', description: 'Rugs, cushions, wall art, and vases', productCount: 55 },
    ],
    defaultProducts: [
      { name: 'Velvet Sectional Sofa', price: 1299.99, originalPrice: 1599.99, description: 'L-shaped velvet sectional with solid wood frame', category: 'Living Room', rating: 4.6, reviewCount: 345, badge: 'Best Seller' },
      { name: 'Oak Dining Table (6-seat)', price: 899.99, description: 'Solid oak dining table with natural grain finish', category: 'Living Room', rating: 4.5, reviewCount: 234 },
      { name: 'King Platform Bed Frame', price: 649.99, originalPrice: 799.99, description: 'Minimalist platform bed with slat support', category: 'Bedroom', rating: 4.7, reviewCount: 567, badge: 'Top Rated' },
      { name: 'Ergonomic Office Chair', price: 449.99, description: 'Adjustable lumbar support, mesh back, 4D armrests', category: 'Office', rating: 4.4, reviewCount: 892 },
      { name: 'Outdoor Teak Lounge Set', price: 1599.99, originalPrice: 1999.99, description: '4-piece teak outdoor lounge with cushions', category: 'Outdoor', rating: 4.5, reviewCount: 123, badge: 'Premium' },
      { name: 'Crystal Chandelier', price: 399.99, description: '24-light crystal chandelier with dimmer', category: 'Lighting', rating: 4.8, reviewCount: 89, badge: 'Luxury' },
      { name: 'Handwoven Area Rug 8x10', price: 299.99, originalPrice: 399.99, description: 'Moroccan-inspired handwoven area rug', category: 'Decor', rating: 4.3, reviewCount: 267 },
      { name: 'Standing Desk Adjustable', price: 599.99, description: 'Electric sit-stand desk with memory presets', category: 'Office', rating: 4.6, reviewCount: 456, badge: 'Popular' },
      { name: 'Velvet Accent Chair', price: 349.99, description: 'Mid-century accent chair with gold legs', category: 'Living Room', rating: 4.4, reviewCount: 198 },
      { name: 'Smart LED Floor Lamp', price: 179.99, originalPrice: 219.99, description: 'Wi-Fi enabled floor lamp with app control', category: 'Lighting', rating: 4.5, reviewCount: 312 },
    ],
    colorSchemes: [
      { primary: '#795548', secondary: '#D7CCC8', label: 'Warm Wood' },
      { primary: '#3E2723', secondary: '#EFEBE9', label: 'Rich Walnut' },
      { primary: '#455A64', secondary: '#CFD8DC', label: 'Modern Grey' },
      { primary: '#8D6E63', secondary: '#F5F0EB', label: 'Oak Natural' },
    ],
    designStyle: {
      themeStyle: 'Sophisticated',
      fontStyle: 'Cormorant Garamond',
      buttonStyle: 'Minimal',
      borderRadius: '4px',
    },
  },

  Beauty: {
    label: 'Beauty & Personal Care',
    icon: '💄',
    categories: [
      { name: 'Skincare', description: 'Cleansers, moisturizers, serums, and SPF', productCount: 58 },
      { name: 'Makeup', description: 'Foundation, lipstick, eyeshadow, and tools', productCount: 72 },
      { name: 'Haircare', description: 'Shampoo, conditioner, treatments, and styling', productCount: 45 },
      { name: 'Fragrances', description: 'Perfumes, colognes, and body mists', productCount: 35 },
      { name: 'Tools & Accessories', description: 'Brushes, sponges, mirrors, and storage', productCount: 28 },
      { name: 'Wellness', description: 'Bath, body, aromatherapy, and supplements', productCount: 32 },
    ],
    defaultProducts: [
      { name: 'Hydrating Serum', price: 38.00, originalPrice: 48.00, description: 'Hyaluronic acid serum for deep hydration', category: 'Skincare', rating: 4.8, reviewCount: 1234, badge: 'Best Seller' },
      { name: 'Matte Liquid Lipstick', price: 24.00, description: 'Long-lasting matte finish, 20+ shades', category: 'Makeup', rating: 4.6, reviewCount: 567 },
      { name: 'Keratin Repair Shampoo', price: 29.99, description: 'Professional keratin treatment for damaged hair', category: 'Haircare', rating: 4.5, reviewCount: 456, badge: 'Salon Favorite' },
      { name: 'Floral Eau de Parfum', price: 85.00, originalPrice: 110.00, description: 'Jasmine and rose notes, 50ml bottle', category: 'Fragrances', rating: 4.7, reviewCount: 345, badge: 'Premium' },
      { name: 'Vitamin C Brightening Cream', price: 42.00, description: '15% Vitamin C with SPF 30 protection', category: 'Skincare', rating: 4.4, reviewCount: 678, badge: 'Editor\'s Pick' },
      { name: 'Professional Brush Set', price: 55.00, originalPrice: 75.00, description: '12-piece cruelty-free brush collection', category: 'Tools & Accessories', rating: 4.6, reviewCount: 234 },
      { name: 'Retinol Night Cream', price: 52.00, description: 'Anti-aging retinol with peptides complex', category: 'Skincare', rating: 4.7, reviewCount: 891 },
      { name: 'Dry Shampoo Foam', price: 18.99, description: 'Cleansing foam for quick refresh between washes', category: 'Haircare', rating: 4.3, reviewCount: 345, badge: 'New' },
      { name: 'Setting Spray Long-Wear', price: 22.00, description: '12-hour makeup setting spray, matte finish', category: 'Makeup', rating: 4.5, reviewCount: 567 },
      { name: 'Bath Bomb Gift Set', price: 34.99, originalPrice: 44.99, description: '6-piece artisan bath bomb collection', category: 'Wellness', rating: 4.6, reviewCount: 234, badge: 'Gift Idea' },
    ],
    colorSchemes: [
      { primary: '#E91E63', secondary: '#FCE4EC', label: 'Pink Luxe' },
      { primary: '#9C27B0', secondary: '#F3E5F5', label: 'Plum Radiance' },
      { primary: '#F8BBD0', secondary: '#FFFFFF', label: 'Soft Blush' },
      { primary: '#AD1457', secondary: '#FCE4EC', label: 'Deep Rose' },
    ],
    designStyle: {
      themeStyle: 'Luxe',
      fontStyle: 'Lora',
      buttonStyle: 'Soft',
      borderRadius: '16px',
    },
  },

  Sports: {
    label: 'Sports & Fitness',
    icon: '⚽',
    categories: [
      { name: 'Fitness', description: 'Weights, resistance bands, and gym equipment', productCount: 45 },
      { name: 'Outdoor', description: 'Hiking, camping, and outdoor adventure gear', productCount: 38 },
      { name: 'Team Sports', description: 'Football, basketball, cricket, and more', productCount: 52 },
      { name: 'Running', description: 'Running shoes, apparel, and accessories', productCount: 42 },
      { name: 'Swimming', description: 'Swimwear, goggles, and pool accessories', productCount: 28 },
      { name: 'Cycling', description: 'Bikes, helmets, and cycling gear', productCount: 35 },
    ],
    defaultProducts: [
      { name: 'Pro Running Shoes', price: 149.99, originalPrice: 179.99, description: 'Lightweight carbon plate racing shoe', category: 'Running', rating: 4.8, reviewCount: 678, badge: 'Best Seller' },
      { name: 'Adjustable Dumbbell Set', price: 349.99, description: '5-50lb adjustable dumbbells with stand', category: 'Fitness', rating: 4.6, reviewCount: 456 },
      { name: 'Yoga Mat Premium', price: 68.00, originalPrice: 85.00, description: '6mm thick, non-slip, eco-friendly TPE', category: 'Fitness', rating: 4.7, reviewCount: 892, badge: 'Top Rated' },
      { name: 'Football Official Match', price: 39.99, description: 'FIFA quality pro match ball', category: 'Team Sports', rating: 4.5, reviewCount: 345 },
      { name: 'Compression Running Tights', price: 79.99, description: 'Moisture-wicking compression tights with pockets', category: 'Running', rating: 4.4, reviewCount: 234 },
      { name: 'Carbon Road Bike', price: 2499.99, originalPrice: 2999.99, description: 'Full carbon frame, Shimano 105 groupset', category: 'Cycling', rating: 4.7, reviewCount: 89, badge: 'Premium' },
      { name: 'Swim Goggles Anti-Fog', price: 34.99, description: 'Anti-fog, UV protection, interchangeable nose bridges', category: 'Swimming', rating: 4.3, reviewCount: 567 },
      { name: 'Resistance Band Set', price: 29.99, originalPrice: 39.99, description: '5 levels, door anchor, carry bag included', category: 'Fitness', rating: 4.6, reviewCount: 1234, badge: 'Budget Pick' },
      { name: 'Basketball Shoes High-Top', price: 159.99, description: 'Ankle support, responsive cushioning', category: 'Team Sports', rating: 4.5, reviewCount: 345 },
      { name: 'Camping Tent 4-Person', price: 249.99, originalPrice: 329.99, description: 'Waterproof, easy setup, UV resistant', category: 'Outdoor', rating: 4.4, reviewCount: 234 },
    ],
    colorSchemes: [
      { primary: '#FF6F00', secondary: '#FFF3E0', label: 'Bold Orange' },
      { primary: '#1B5E20', secondary: '#E8F5E9', label: 'Victory Green' },
      { primary: '#D32F2F', secondary: '#FFEBEE', label: 'Power Red' },
      { primary: '#0D47A1', secondary: '#E3F2FD', label: 'Champion Blue' },
    ],
    designStyle: {
      themeStyle: 'Dynamic',
      fontStyle: 'Montserrat',
      buttonStyle: 'Athletic',
      borderRadius: '8px',
    },
  },

  Jewelry: {
    label: 'Jewelry & Watches',
    icon: '💎',
    categories: [
      { name: 'Rings', description: 'Engagement, wedding, and fashion rings', productCount: 65 },
      { name: 'Necklaces', description: 'Pendants, chains, and statement necklaces', productCount: 48 },
      { name: 'Bracelets', description: 'Tennis bracelets, bangles, and cuffs', productCount: 38 },
      { name: 'Earrings', description: 'Studs, hoops, drops, and chandeliers', productCount: 52 },
      { name: 'Watches', description: 'Luxury, fashion, and smartwatches', productCount: 42 },
      { name: 'Collections', description: 'Curated sets and gift collections', productCount: 25 },
    ],
    defaultProducts: [
      { name: 'Diamond Solitaire Ring', price: 2499.99, description: '1ct VS1 clarity diamond, 14K white gold setting', category: 'Rings', rating: 4.9, reviewCount: 234, badge: 'Best Seller' },
      { name: 'Pearl Pendant Necklace', price: 299.99, originalPrice: 399.99, description: 'South Sea pearl on 18" gold chain', category: 'Necklaces', rating: 4.7, reviewCount: 456 },
      { name: 'Gold Tennis Bracelet', price: 1299.99, description: '2ct total weight diamonds, 14K gold', category: 'Bracelets', rating: 4.8, reviewCount: 123, badge: 'Premium' },
      { name: 'Diamond Stud Earrings', price: 899.99, originalPrice: 1099.99, description: '0.5ct each, VS2 clarity, 14K gold', category: 'Earrings', rating: 4.6, reviewCount: 567, badge: 'Popular' },
      { name: 'Luxury Automatic Watch', price: 3499.99, description: 'Swiss movement, sapphire crystal, leather strap', category: 'Watches', rating: 4.9, reviewCount: 89, badge: 'Luxury' },
      { name: 'Emerald Halo Necklace', price: 1899.99, description: 'Natural emerald with diamond halo, 18K gold', category: 'Necklaces', rating: 4.7, reviewCount: 67 },
      { name: 'Silver Charm Bracelet', price: 149.99, originalPrice: 189.99, description: 'Sterling silver with 5 initial charms', category: 'Bracelets', rating: 4.5, reviewCount: 345 },
      { name: 'Ruby Drop Earrings', price: 799.99, description: 'Natural rubies in 14K rose gold drops', category: 'Earrings', rating: 4.8, reviewCount: 123 },
      { name: 'Bridal Set - 3 Piece', price: 4999.99, originalPrice: 5999.99, description: 'Engagement ring + wedding band set, 1.5ct total', category: 'Rings', rating: 4.9, reviewCount: 89, badge: 'Exclusive' },
      { name: 'Men\'s Signet Ring', price: 399.99, description: '10K gold signet with onyx inlay', category: 'Rings', rating: 4.4, reviewCount: 234 },
    ],
    colorSchemes: [
      { primary: '#FFD700', secondary: '#FFFDE7', label: 'Gold Luxe' },
      { primary: '#212121', secondary: '#F5F5F5', label: 'Black Diamond' },
      { primary: '#E8EAF6', secondary: '#FFFFFF', label: 'Platinum Pure' },
      { primary: '#B71C1C', secondary: '#FFEBEE', label: 'Ruby Red' },
    ],
    designStyle: {
      themeStyle: 'Luxurious',
      fontStyle: 'Playfair Display',
      buttonStyle: 'Elegant',
      borderRadius: '4px',
    },
  },

  Books: {
    label: 'Books & Publishing',
    icon: '📚',
    categories: [
      { name: 'Fiction', description: 'Literary fiction, thrillers, romance, and sci-fi', productCount: 120 },
      { name: 'Non-Fiction', description: 'Biography, history, self-help, and science', productCount: 85 },
      { name: 'Academic', description: 'Textbooks, reference, and educational', productCount: 95 },
      { name: 'Children', description: 'Picture books, middle grade, and young adult', productCount: 75 },
      { name: 'Comics & Graphic', description: 'Graphic novels, manga, and comics', productCount: 60 },
      { name: 'Bestsellers', description: 'Top selling books and new releases', productCount: 40 },
    ],
    defaultProducts: [
      { name: 'The Silent Echo', price: 24.99, originalPrice: 29.99, description: 'A gripping mystery thriller by debut author', category: 'Fiction', rating: 4.7, reviewCount: 1234, badge: 'Best Seller' },
      { name: 'Quantum Thinking', price: 19.99, description: 'Unlock your potential with science-backed strategies', category: 'Non-Fiction', rating: 4.5, reviewCount: 567, badge: 'Editor\'s Pick' },
      { name: 'Advanced Calculus Textbook', price: 89.99, originalPrice: 119.99, description: '8th edition, comprehensive coverage', category: 'Academic', rating: 4.3, reviewCount: 345 },
      { name: 'Dragons & Dreams (Box Set)', price: 49.99, description: 'Complete 4-book fantasy series for young readers', category: 'Children', rating: 4.8, reviewCount: 892, badge: 'Value Set' },
      { name: 'Star Force Chronicles Vol. 1', price: 14.99, description: 'Epic sci-fi graphic novel adventure', category: 'Comics & Graphic', rating: 4.6, reviewCount: 234 },
      { name: 'Mindful Living', price: 22.99, description: 'A guide to finding peace in a busy world', category: 'Non-Fiction', rating: 4.7, reviewCount: 678, badge: 'Popular' },
      { name: 'Romance in Paris', price: 16.99, originalPrice: 21.99, description: 'A charming contemporary romance novel', category: 'Fiction', rating: 4.4, reviewCount: 456 },
      { name: 'History of Innovation', price: 34.99, description: 'Illustrated history of human invention', category: 'Non-Fiction', rating: 4.6, reviewCount: 123 },
      { name: 'Mathematics for Kids', price: 12.99, description: 'Fun math adventures for ages 6-10', category: 'Children', rating: 4.8, reviewCount: 345, badge: 'Award Winner' },
      { name: 'Manga: Spirit Warriors', price: 9.99, description: 'Action-packed manga series starter', category: 'Comics & Graphic', rating: 4.5, reviewCount: 567 },
    ],
    colorSchemes: [
      { primary: '#5D4037', secondary: '#EFEBE9', label: 'Classic Library' },
      { primary: '#1565C0', secondary: '#E3F2FD', label: 'Literary Blue' },
      { primary: '#4E342E', secondary: '#F5F0EB', label: 'Vintage Paper' },
      { primary: '#33691E', secondary: '#F1F8E9', label: 'Reading Green' },
    ],
    designStyle: {
      themeStyle: 'Classic',
      fontStyle: 'Merriweather',
      buttonStyle: 'Traditional',
      borderRadius: '6px',
    },
  },

  Restaurant: {
    label: 'Restaurant & Food',
    icon: '🍽️',
    categories: [
      { name: 'Appetizers', description: 'Starters, small plates, and shared dishes', productCount: 25 },
      { name: 'Mains', description: 'Entrees, signature dishes, and platters', productCount: 35 },
      { name: 'Desserts', description: 'Cakes, pastries, and sweet treats', productCount: 20 },
      { name: 'Drinks', description: 'Beverages, cocktails, and specialty drinks', productCount: 30 },
      { name: 'Specials', description: 'Daily specials and chef\'s recommendations', productCount: 12 },
      { name: 'Catering', description: 'Party platters and catering packages', productCount: 15 },
    ],
    defaultProducts: [
      { name: 'Truffle Mushroom Bruschetta', price: 14.99, description: 'Grilled sourdough with truffle mushroom tapenade', category: 'Appetizers', rating: 4.7, reviewCount: 345, badge: 'Chef\'s Pick' },
      { name: 'Grilled Salmon', price: 28.99, originalPrice: 34.99, description: 'Atlantic salmon with lemon butter sauce', category: 'Mains', rating: 4.8, reviewCount: 567, badge: 'Popular' },
      { name: 'Tiramisu', price: 12.99, description: 'Classic Italian tiramisu with mascarpone', category: 'Desserts', rating: 4.9, reviewCount: 892, badge: 'Best Seller' },
      { name: 'Signature Cocktail', price: 15.99, description: 'Chef\'s special seasonal cocktail', category: 'Drinks', rating: 4.5, reviewCount: 234 },
      { name: 'Party Platter (10 people)', price: 149.99, originalPrice: 189.99, description: 'Assorted appetizers and finger foods', category: 'Catering', rating: 4.6, reviewCount: 123 },
      { name: 'Pasta Carbonara', price: 19.99, description: 'Traditional spaghetti carbonara with pancetta', category: 'Mains', rating: 4.6, reviewCount: 456 },
      { name: 'Fresh Garden Salad', price: 11.99, description: 'Mixed greens with house vinaigrette', category: 'Appetizers', rating: 4.3, reviewCount: 345 },
      { name: 'Chocolate Lava Cake', price: 14.99, description: 'Warm chocolate cake with molten center', category: 'Desserts', rating: 4.7, reviewCount: 678 },
      { name: 'Wine Pairing Flight', price: 24.99, description: '3 premium wines curated by our sommelier', category: 'Drinks', rating: 4.8, reviewCount: 89 },
      { name: 'Weekend Brunch Special', price: 32.99, originalPrice: 42.99, description: 'Full brunch menu with bottomless mimosas', category: 'Specials', rating: 4.9, reviewCount: 234, badge: 'Weekend Only' },
    ],
    colorSchemes: [
      { primary: '#D84315', secondary: '#FFCCBC', label: 'Warm Terracotta' },
      { primary: '#33691E', secondary: '#DCEDC8', label: 'Fresh Garden' },
      { primary: '#BF360C', secondary: '#FF8A65', label: 'Bold Spice' },
      { primary: '#4E342E', secondary: '#D7CCC8', label: 'Rustic Wood' },
    ],
    designStyle: {
      themeStyle: 'Inviting',
      fontStyle: 'Open Sans',
      buttonStyle: 'Warm',
      borderRadius: '12px',
    },
  },

  Healthcare: {
    label: 'Healthcare & Medical',
    icon: '🏥',
    categories: [
      { name: 'Clinics', description: 'Primary care, specialists, and walk-ins', productCount: 30 },
      { name: 'Pharmacies', description: 'Prescription and OTC medications', productCount: 45 },
      { name: 'Wellness', description: 'Supplements, vitamins, and health products', productCount: 55 },
      { name: 'Diagnostics', description: 'Lab tests, imaging, and health screenings', productCount: 25 },
      { name: 'Specialties', description: 'Dental, vision, dermatology, and more', productCount: 35 },
      { name: 'Telehealth', description: 'Virtual consultations and online services', productCount: 20 },
    ],
    defaultProducts: [
      { name: 'General Health Checkup', price: 149.99, description: 'Comprehensive annual health examination', category: 'Clinics', rating: 4.8, reviewCount: 567, badge: 'Popular' },
      { name: 'Complete Blood Panel', price: 89.99, originalPrice: 119.99, description: 'Full metabolic panel with lipid profile', category: 'Diagnostics', rating: 4.7, reviewCount: 892 },
      { name: 'Dental Cleaning & Exam', price: 129.99, description: 'Professional cleaning with x-rays', category: 'Specialties', rating: 4.6, reviewCount: 345 },
      { name: 'Vitamin D Supplement (90ct)', price: 24.99, description: '5000 IU Vitamin D3 softgels', category: 'Wellness', rating: 4.5, reviewCount: 1234, badge: 'Best Seller' },
      { name: 'Virtual Consultation (30 min)', price: 79.99, description: 'Video consultation with licensed physician', category: 'Telehealth', rating: 4.4, reviewCount: 456 },
      { name: 'Vision Exam + Contacts', price: 199.99, originalPrice: 249.99, description: 'Eye exam with contact lens fitting', category: 'Specialties', rating: 4.7, reviewCount: 234 },
      { name: 'Allergy Panel Test', price: 159.99, description: 'Comprehensive allergy testing (40+ allergens)', category: 'Diagnostics', rating: 4.6, reviewCount: 123 },
      { name: 'Omega-3 Fish Oil (60ct)', price: 29.99, description: 'Triple strength EPA/DHA supplement', category: 'Wellness', rating: 4.4, reviewCount: 678 },
      { name: 'Mental Health Session', price: 120.00, description: '45-minute therapy session (in-person/virtual)', category: 'Specialties', rating: 4.8, reviewCount: 345, badge: 'Essential' },
      { name: 'Home Health Kit', price: 59.99, originalPrice: 79.99, description: 'BP monitor, thermometer, pulse oximeter', category: 'Wellness', rating: 4.5, reviewCount: 234 },
    ],
    colorSchemes: [
      { primary: '#0277BD', secondary: '#E1F5FE', label: 'Medical Blue' },
      { primary: '#00897B', secondary: '#E0F2F1', label: 'Healing Teal' },
      { primary: '#2E7D32', secondary: '#E8F5E9', label: 'Health Green' },
      { primary: '#37474F', secondary: '#ECEFF1', label: 'Clinical Grey' },
    ],
    designStyle: {
      themeStyle: 'Clean',
      fontStyle: 'Source Sans Pro',
      buttonStyle: 'Trustworthy',
      borderRadius: '8px',
    },
  },

  Education: {
    label: 'Education & Learning',
    icon: '🎓',
    categories: [
      { name: 'Courses', description: 'Online courses, certifications, and degrees', productCount: 85 },
      { name: 'Certifications', description: 'Professional certifications and exams', productCount: 45 },
      { name: 'Workshops', description: 'Live workshops and bootcamps', productCount: 35 },
      { name: 'Resources', description: 'Ebooks, templates, and study materials', productCount: 65 },
      { name: 'Programs', description: 'Degree programs and learning paths', productCount: 25 },
      { name: 'Tutoring', description: 'One-on-one and group tutoring sessions', productCount: 30 },
    ],
    defaultProducts: [
      { name: 'Web Development Bootcamp', price: 499.99, originalPrice: 799.99, description: 'Full-stack web development in 12 weeks', category: 'Courses', rating: 4.8, reviewCount: 2345, badge: 'Best Seller' },
      { name: 'Data Science Certificate', price: 899.99, description: 'Comprehensive data science with Python', category: 'Certifications', rating: 4.7, reviewCount: 567, badge: 'Top Rated' },
      { name: 'Digital Marketing Workshop', price: 149.99, originalPrice: 199.99, description: '2-day intensive digital marketing workshop', category: 'Workshops', rating: 4.5, reviewCount: 892 },
      { name: 'Python Programming E-Book', price: 29.99, description: 'Complete guide to Python programming', category: 'Resources', rating: 4.6, reviewCount: 1234 },
      { name: 'UX Design Learning Path', price: 299.99, originalPrice: 449.99, description: '6-month comprehensive UX design program', category: 'Programs', rating: 4.7, reviewCount: 345 },
      { name: 'Math Tutoring (10 sessions)', price: 299.99, description: 'Personalized math tutoring for grades 6-12', category: 'Tutoring', rating: 4.8, reviewCount: 234, badge: 'Popular' },
      { name: 'AI & Machine Learning Course', price: 699.99, originalPrice: 999.99, description: 'Advanced AI course with hands-on projects', category: 'Courses', rating: 4.9, reviewCount: 456, badge: 'New' },
      { name: 'Business English Bundle', price: 199.99, description: 'Complete business English course + materials', category: 'Courses', rating: 4.4, reviewCount: 678 },
      { name: 'AWS Cloud Certification', price: 399.99, description: 'AWS Solutions Architect certification prep', category: 'Certifications', rating: 4.6, reviewCount: 345 },
      { name: 'Kids Coding Camp (1 week)', price: 249.99, originalPrice: 349.99, description: 'Scratch & Python coding for ages 8-14', category: 'Workshops', rating: 4.7, reviewCount: 123 },
    ],
    colorSchemes: [
      { primary: '#1565C0', secondary: '#E3F2FD', label: 'Academic Blue' },
      { primary: '#6A1B9A', secondary: '#F3E5F5', label: 'Scholar Purple' },
      { primary: '#00695C', secondary: '#E0F2F1', label: 'Growth Teal' },
      { primary: '#E65100', secondary: '#FFF3E0', label: 'Energetic Orange' },
    ],
    designStyle: {
      themeStyle: 'Professional',
      fontStyle: 'Poppins',
      buttonStyle: 'Bold',
      borderRadius: '10px',
    },
  },

  'Real Estate': {
    label: 'Real Estate',
    icon: '🏠',
    categories: [
      { name: 'Residential', description: 'Houses, apartments, and condos for sale', productCount: 120 },
      { name: 'Commercial', description: 'Office spaces, retail, and warehouses', productCount: 65 },
      { name: 'Rental', description: 'Short-term and long-term rentals', productCount: 85 },
      { name: 'Luxury', description: 'High-end properties and penthouses', productCount: 35 },
      { name: 'Land', description: 'Plots, lots, and development land', productCount: 45 },
      { name: 'Industrial', description: 'Factories, workshops, and storage facilities', productCount: 30 },
    ],
    defaultProducts: [
      { name: 'Modern Family Home', price: 485000, description: '4BR/3BA, 2,400 sqft, pool, updated kitchen', category: 'Residential', rating: 4.7, reviewCount: 23, badge: 'New Listing' },
      { name: 'Downtown Luxury Condo', price: 329900, originalPrice: 349900, description: '2BR/2BA, city views, doorman building', category: 'Residential', rating: 4.5, reviewCount: 15 },
      { name: 'Office Space - Class A', price: 3500, description: '2,500 sqft, downtown location, parking included', category: 'Commercial', rating: 4.6, reviewCount: 8 },
      { name: 'Beachfront Villa', price: 1250000, description: '5BR/4BA, oceanfront, private beach access', category: 'Luxury', rating: 4.9, reviewCount: 12, badge: 'Premium' },
      { name: '1 Acre Development Land', price: 175000, description: 'Zoned residential, utilities at street', category: 'Land', rating: 4.3, reviewCount: 6 },
      { name: 'Cozy Studio Rental', price: 1400, description: 'Studio/1BA, furnished, utilities included', category: 'Rental', rating: 4.4, reviewCount: 34, badge: 'Available Now' },
      { name: 'Warehouse Facility', price: 890000, description: '15,000 sqft, loading dock, office space', category: 'Industrial', rating: 4.5, reviewCount: 5 },
      { name: 'Suburban Townhome', price: 299900, description: '3BR/2.5BA, HOA maintained, garage', category: 'Residential', rating: 4.6, reviewCount: 19, badge: 'Open House' },
      { name: 'Penthouse Suite', price: 2500000, description: '4BR/4BA, panoramic views, private elevator', category: 'Luxury', rating: 4.9, reviewCount: 7 },
      { name: 'Vacation Rental Cabin', price: 250, description: '2BR, mountain views, hot tub, sleeps 6', category: 'Rental', rating: 4.8, reviewCount: 45 },
    ],
    colorSchemes: [
      { primary: '#1B5E20', secondary: '#E8F5E9', label: 'Trust Green' },
      { primary: '#0D47A1', secondary: '#E3F2FD', label: 'Professional Blue' },
      { primary: '#455A64', secondary: '#ECEFF1', label: 'Elegant Grey' },
      { primary: '#3E2723', secondary: '#EFEBE9', label: 'Classic Brown' },
    ],
    designStyle: {
      themeStyle: 'Professional',
      fontStyle: 'Roboto',
      buttonStyle: 'Professional',
      borderRadius: '6px',
    },
  },

  Travel: {
    label: 'Travel & Tourism',
    icon: '✈️',
    categories: [
      { name: 'Flights', description: 'Domestic and international flights', productCount: 85 },
      { name: 'Hotels', description: 'Hotels, resorts, and boutique stays', productCount: 120 },
      { name: 'Packages', description: 'All-inclusive vacation packages', productCount: 45 },
      { name: 'Tours', description: 'Guided tours and experiences', productCount: 65 },
      { name: 'Cruises', description: 'Cruise packages and deals', productCount: 30 },
      { name: 'Activities', description: 'Excursions, tickets, and experiences', productCount: 80 },
    ],
    defaultProducts: [
      { name: 'Maldives Paradise Package', price: 2499, originalPrice: 3299, description: '7 nights all-inclusive, overwater villa', category: 'Packages', rating: 4.9, reviewCount: 567, badge: 'Best Seller' },
      { name: 'Round Trip Flight NYC-London', price: 649, description: 'Economy class, direct flight, flexible ticket', category: 'Flights', rating: 4.5, reviewCount: 1234 },
      { name: 'Bali Beach Resort', price: 189, originalPrice: 249, description: '5-star beachfront resort, breakfast included', category: 'Hotels', rating: 4.7, reviewCount: 892, badge: 'Top Rated' },
      { name: 'Swiss Alps Adventure Tour', price: 1899, description: '10-day guided tour, 5 countries', category: 'Tours', rating: 4.8, reviewCount: 345, badge: 'Adventure' },
      { name: 'Caribbean Cruise (7 nights)', price: 1299, originalPrice: 1799, description: 'All-inclusive cruise, 4 ports of call', category: 'Cruises', rating: 4.6, reviewCount: 456 },
      { name: 'Santorini Sunset Experience', price: 149, description: 'Catamaran cruise with dinner', category: 'Activities', rating: 4.9, reviewCount: 678, badge: 'Romantic' },
      { name: 'Tokyo City Break', price: 1599, description: '5 nights hotel + tours + bullet train pass', category: 'Packages', rating: 4.7, reviewCount: 234 },
      { name: 'Safari Adventure Kenya', price: 3499, originalPrice: 4199, description: '8-day luxury safari, 5-star lodges', category: 'Tours', rating: 4.9, reviewCount: 123, badge: 'Premium' },
      { name: 'Budget Europe Rail Pass', price: 399, description: '15-day unlimited rail travel, 33 countries', category: 'Activities', rating: 4.4, reviewCount: 567 },
      { name: 'Ski Resort Package', price: 1199, description: '7 nights + lift passes + equipment rental', category: 'Packages', rating: 4.6, reviewCount: 198 },
    ],
    colorSchemes: [
      { primary: '#0277BD', secondary: '#E1F5FE', label: 'Ocean Blue' },
      { primary: '#FF6F00', secondary: '#FFF3E0', label: 'Sunset Orange' },
      { primary: '#00838F', secondary: '#E0F7FA', label: 'Tropical Teal' },
      { primary: '#558B2F', secondary: '#F1F8E9', label: 'Adventure Green' },
    ],
    designStyle: {
      themeStyle: 'Inspiring',
      fontStyle: 'Nunito Sans',
      buttonStyle: 'Adventurous',
      borderRadius: '12px',
    },
  },

  'Pet Store': {
    label: 'Pet Store & Supplies',
    icon: '🐾',
    categories: [
      { name: 'Dogs', description: 'Food, toys, and accessories for dogs', productCount: 85 },
      { name: 'Cats', description: 'Food, litter, and toys for cats', productCount: 72 },
      { name: 'Fish', description: 'Aquariums, food, and tank supplies', productCount: 45 },
      { name: 'Birds', description: 'Cages, feeders, and bird toys', productCount: 35 },
      { name: 'Reptiles', description: 'Terrariums, heat lamps, and reptile food', productCount: 25 },
      { name: 'Accessories', description: 'Leashes, beds, grooming, and carriers', productCount: 55 },
    ],
    defaultProducts: [
      { name: 'Premium Dog Food (25lb)', price: 54.99, originalPrice: 64.99, description: 'Grain-free chicken recipe for adults', category: 'Dogs', rating: 4.7, reviewCount: 1234, badge: 'Best Seller' },
      { name: 'Cat Scratching Post Tower', price: 79.99, description: 'Multi-level sisal scratching post with perch', category: 'Cats', rating: 4.6, reviewCount: 567 },
      { name: 'LED Aquarium Kit (20gal)', price: 129.99, originalPrice: 159.99, description: 'Complete starter kit with filter and light', category: 'Fish', rating: 4.5, reviewCount: 345, badge: 'Great Value' },
      { name: 'Interactive Dog Toy Bundle', price: 34.99, description: '10-piece assorted puzzle and chew toys', category: 'Dogs', rating: 4.8, reviewCount: 892, badge: 'Top Rated' },
      { name: 'Cat Litter Self-Cleaning', price: 249.99, originalPrice: 299.99, description: 'Automated self-cleaning litter box', category: 'Cats', rating: 4.4, reviewCount: 234 },
      { name: 'Bird Cage Deluxe', price: 149.99, description: 'Large flight cage with accessories', category: 'Birds', rating: 4.6, reviewCount: 123 },
      { name: 'Reptile Terrarium Kit', price: 189.99, originalPrice: 229.99, description: '40-gallon tank with heat lamp and decor', category: 'Reptiles', rating: 4.5, reviewCount: 89 },
      { name: 'Orthopedic Dog Bed', price: 69.99, description: 'Memory foam bed for senior dogs, XL size', category: 'Accessories', rating: 4.7, reviewCount: 456, badge: 'Popular' },
      { name: 'Dog Harness No-Pull', price: 29.99, originalPrice: 39.99, description: 'Adjustable no-pull harness with reflective trim', category: 'Accessories', rating: 4.6, reviewCount: 678 },
      { name: 'Cat Indoor Garden', price: 39.99, description: 'Cat grass and catnip growing kit', category: 'Cats', rating: 4.3, reviewCount: 198 },
    ],
    colorSchemes: [
      { primary: '#FF8F00', secondary: '#FFF8E1', label: 'Happy Orange' },
      { primary: '#558B2F', secondary: '#F1F8E9', label: 'Nature Green' },
      { primary: '#5D4037', secondary: '#EFEBE9', label: 'Warm Brown' },
      { primary: '#0277BD', secondary: '#E1F5FE', label: 'Trust Blue' },
    ],
    designStyle: {
      themeStyle: 'Playful',
      fontStyle: 'Quicksand',
      buttonStyle: 'Fun',
      borderRadius: '16px',
    },
  },

  Automotive: {
    label: 'Automotive & Vehicles',
    icon: '🚗',
    categories: [
      { name: 'Cars', description: 'Sedans, coupes, and hatchbacks', productCount: 45 },
      { name: 'Trucks', description: 'Pickup trucks and commercial vehicles', productCount: 30 },
      { name: 'SUVs', description: 'Compact and full-size SUVs', productCount: 38 },
      { name: 'EVs', description: 'Electric and hybrid vehicles', productCount: 22 },
      { name: 'Parts', description: 'Auto parts, tires, and accessories', productCount: 120 },
      { name: 'Services', description: 'Maintenance, repair, and detailing', productCount: 40 },
    ],
    defaultProducts: [
      { name: '2026 Sedan Pro', price: 28990, description: '35 MPG, 201hp, Apple CarPlay, safety suite', category: 'Cars', rating: 4.6, reviewCount: 345, badge: 'Popular' },
      { name: 'Electric SUV Long Range', price: 52990, originalPrice: 56990, description: '350mi range, AWD, autopilot capable', category: 'EVs', rating: 4.8, reviewCount: 567, badge: 'Editor\'s Choice' },
      { name: 'Full-Size Pickup Truck', price: 45990, description: 'Towing capacity 12,000lb, crew cab', category: 'Trucks', rating: 4.5, reviewCount: 234 },
      { name: 'Compact SUV', price: 32990, originalPrice: 35990, description: '30 MPG, spacious interior, AWD available', category: 'SUVs', rating: 4.6, reviewCount: 456, badge: 'Best Value' },
      { name: 'Premium All-Season Tires (Set of 4)', price: 699.99, originalPrice: 849.99, description: '225/65R17, 60,000 mile warranty', category: 'Parts', rating: 4.7, reviewCount: 892, badge: 'Best Seller' },
      { name: 'Full Service Maintenance', price: 299.99, description: 'Oil change, tire rotation, inspection', category: 'Services', rating: 4.5, reviewCount: 1234 },
      { name: 'Ceramic Coating Package', price: 899.99, originalPrice: 1199.99, description: 'Professional paint protection, 5 year warranty', category: 'Services', rating: 4.8, reviewCount: 345, badge: 'Premium' },
      { name: 'Performance Exhaust System', price: 599.99, description: 'Cat-back exhaust, stainless steel', category: 'Parts', rating: 4.4, reviewCount: 198 },
      { name: 'Hybrid Crossover', price: 36990, description: '50 MPG combined, spacious, tech-packed', category: 'EVs', rating: 4.6, reviewCount: 234 },
      { name: 'Winter Tire Package', price: 899.99, originalPrice: 1099.99, description: '4 winter tires + steel wheels + installation', category: 'Parts', rating: 4.7, reviewCount: 456, badge: 'Seasonal' },
    ],
    colorSchemes: [
      { primary: '#B71C1C', secondary: '#FFEBEE', label: 'Racing Red' },
      { primary: '#212121', secondary: '#E0E0E0', label: 'Sleek Black' },
      { primary: '#0D47A1', secondary: '#E3F2FD', label: 'Metallic Blue' },
      { primary: '#37474F', secondary: '#CFD8DC', label: 'Steel Grey' },
    ],
    designStyle: {
      themeStyle: 'Bold',
      fontStyle: 'Barlow',
      buttonStyle: 'Powerful',
      borderRadius: '8px',
    },
  },

  'Home Services': {
    label: 'Home Services',
    icon: '🔧',
    categories: [
      { name: 'Cleaning', description: 'House cleaning, deep cleaning, and move-out', productCount: 25 },
      { name: 'Plumbing', description: 'Repairs, installations, and emergencies', productCount: 30 },
      { name: 'Electrical', description: 'Wiring, repairs, and installations', productCount: 28 },
      { name: 'Painting', description: 'Interior, exterior, and commercial painting', productCount: 22 },
      { name: 'Landscaping', description: 'Lawn care, garden design, and maintenance', productCount: 35 },
      { name: 'HVAC', description: 'Heating, cooling, and ventilation services', productCount: 25 },
    ],
    defaultProducts: [
      { name: 'Deep Clean Package', price: 249.99, originalPrice: 299.99, description: 'Full home deep clean, all rooms included', category: 'Cleaning', rating: 4.8, reviewCount: 567, badge: 'Most Popular' },
      { name: 'Plumbing Emergency Fix', price: 189.99, description: 'Emergency plumbing repair, 24/7 availability', category: 'Plumbing', rating: 4.6, reviewCount: 345 },
      { name: 'Interior Painting (Per Room)', price: 349.99, originalPrice: 449.99, description: 'Professional painting, 2 coats, trim included', category: 'Painting', rating: 4.7, reviewCount: 234 },
      { name: 'Lawn Care Monthly', price: 129.99, description: 'Weekly mowing, edging, and blowing', category: 'Landscaping', rating: 4.5, reviewCount: 892, badge: 'Best Value' },
      { name: 'HVAC Tune-Up', price: 149.99, description: 'Complete system inspection and maintenance', category: 'HVAC', rating: 4.6, reviewCount: 456 },
      { name: 'Electrical Panel Upgrade', price: 1899.99, originalPrice: 2299.99, description: '200-amp panel upgrade, permits included', category: 'Electrical', rating: 4.7, reviewCount: 123, badge: 'Premium' },
      { name: 'Move-Out Cleaning', price: 349.99, description: 'Top-to-bottom cleaning for move-out', category: 'Cleaning', rating: 4.8, reviewCount: 234, badge: 'Guaranteed' },
      { name: 'Garden Design Consultation', price: 199.99, description: 'Professional landscape design plan', category: 'Landscaping', rating: 4.5, reviewCount: 89 },
      { name: 'Water Heater Installation', price: 1499.99, originalPrice: 1799.99, description: 'New 50-gallon water heater, removal included', category: 'Plumbing', rating: 4.6, reviewCount: 198 },
      { name: 'AC System Installation', price: 3999.99, description: 'Central AC system, 3-ton, professional install', category: 'HVAC', rating: 4.7, reviewCount: 67 },
    ],
    colorSchemes: [
      { primary: '#1565C0', secondary: '#E3F2FD', label: 'Trust Blue' },
      { primary: '#F57F17', secondary: '#FFF9C4', label: 'Warning Orange' },
      { primary: '#2E7D32', secondary: '#E8F5E9', label: 'Eco Green' },
      { primary: '#455A64', secondary: '#ECEFF1', label: 'Professional Grey' },
    ],
    designStyle: {
      themeStyle: 'Reliable',
      fontStyle: 'Open Sans',
      buttonStyle: 'Action-Oriented',
      borderRadius: '8px',
    },
  },

  Other: {
    label: 'General E-Commerce',
    icon: '🛍️',
    categories: [
      { name: 'Featured', description: 'Our top featured products', productCount: 50 },
      { name: 'New Arrivals', description: 'Latest additions to our catalog', productCount: 40 },
      { name: 'Best Sellers', description: 'Most popular products', productCount: 35 },
      { name: 'Sale', description: 'Discounted and clearance items', productCount: 45 },
      { name: 'Gifts', description: 'Perfect gift ideas for all occasions', productCount: 30 },
      { name: 'Essentials', description: 'Everyday essentials and must-haves', productCount: 55 },
    ],
    defaultProducts: [
      { name: 'Classic Essential Tee', price: 29.99, description: 'Premium cotton tee, available in 10 colors', category: 'Essentials', rating: 4.5, reviewCount: 567, badge: 'Best Seller' },
      { name: 'Pro Wireless Headphones', price: 149.99, originalPrice: 199.99, description: 'Noise-cancelling, 30hr battery life', category: 'Featured', rating: 4.7, reviewCount: 892 },
      { name: 'Smart Watch Series 5', price: 299.99, description: 'Health tracking, GPS, 7-day battery', category: 'New Arrivals', rating: 4.6, reviewCount: 345, badge: 'New' },
      { name: 'Canvas Tote Bag', price: 39.99, originalPrice: 54.99, description: 'Durable canvas with leather straps', category: 'Essentials', rating: 4.4, reviewCount: 234 },
      { name: 'Aromatherapy Candle Set', price: 44.99, description: 'Set of 3 soy candles, assorted scents', category: 'Gifts', rating: 4.8, reviewCount: 678, badge: 'Popular' },
      { name: 'Fitness Tracker Band', price: 79.99, originalPrice: 99.99, description: 'Heart rate, sleep tracking, waterproof', category: 'Featured', rating: 4.5, reviewCount: 456 },
      { name: 'Premium Journal Notebook', price: 24.99, description: 'Leather-bound, 200 pages, lay-flat binding', category: 'Essentials', rating: 4.6, reviewCount: 345 },
      { name: 'Portable Bluetooth Speaker', price: 69.99, originalPrice: 89.99, description: 'Waterproof, 12hr playtime, compact design', category: 'New Arrivals', rating: 4.4, reviewCount: 567 },
      { name: 'Gift Box Collection', price: 59.99, description: 'Curated gift box with assorted goodies', category: 'Gifts', rating: 4.7, reviewCount: 123, badge: 'Gift Idea' },
      { name: 'Sale Bundle Pack', price: 34.99, originalPrice: 59.99, description: '3-piece assorted essentials bundle', category: 'Sale', rating: 4.3, reviewCount: 234, badge: '40% Off' },
    ],
    colorSchemes: [
      { primary: '#3F51B5', secondary: '#C5CAE9', label: 'Indigo Trust' },
      { primary: '#009688', secondary: '#B2DFDB', label: 'Teal Fresh' },
      { primary: '#795548', secondary: '#D7CCC8', label: 'Warm Neutral' },
      { primary: '#607D8B', secondary: '#CFD8DC', label: 'Slate Professional' },
    ],
    designStyle: {
      themeStyle: 'Versatile',
      fontStyle: 'Lato',
      buttonStyle: 'Neutral',
      borderRadius: '10px',
    },
  },
};
